home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('page/<int:page>', views.index, name='index'),
    path('robots.txt', views.robots, name='robots.txt'),
]

lemonauth/urls.py
from django.urls import path
from . import views

app_name = 'lemonauth'
urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('indie', views.IndieView.as_view(), name='indie'),
    path('indie/approve', views.indie_approve, name='indie_approve'),
    path('token', views.TokenView.as_view(), name='token'),
]

lemoncurry/urls.py
from typing import Tuple

from django.conf import settings
from django.urls import include, path
from django.urls.resolvers import URLPattern
from django.views.generic import RedirectView

from django.contrib import admin
import django.contrib.sitemaps.views as sitemap

from entries.sitemaps import EntriesSitemap
from home.sitemaps import HomeSitemap

sections = {
    'entries': EntriesSitemap,
    'home': HomeSitemap,
}
maps = {'sitemaps': sections}

urlpatterns = (
    path('', include('home.urls')),
    path('', include('entries.urls')),
    path('', include('users.urls')),
    path('.well-known/', include('wellknowns.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('lemonauth.urls')),
    path('favicon.ico', RedirectView.as_view(
        url=settings.MEDIA_URL + 'favicon/favicon.ico')),
    path('micropub', include('micropub.urls')),
    path('s/', include('lemonshort.urls')),
    path('webmention', include('webmention.urls')),

    path('django-rq/', include('django_rq.urls')),
    path('sitemap.xml', sitemap.index, maps, name='sitemap'),
    path('sitemaps/<section>.xml', sitemap.sitemap, maps,
         name='django.contrib.sitemaps.views.sitemap'),
)  # type: Tuple[URLPattern, ...]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (
        path('__debug__/', include(debug_toolbar.urls)),
    )

micropub/urls.py
from django.urls import path
from .views import micropub
from .views.media import media

app_name = 'micropub'
urlpatterns = (
    path('', micropub, name='micropub'),
    path('/media', media, name='media'),
)

wellknowns/urls.py
from django.urls import path

from . import views

app_name = 'wellknowns'
urlpatterns = [
    path('keybase.txt', views.keybase, name='keybase'),
    path('host-meta', views.host_meta_xml, name='host-meta'),
    path('host-meta.json', views.host_meta_json, name='host-meta.json'),
    path('manifest.json', views.manifest, name='manifest'),
    path('webfinger', views.webfinger, name='webfinger'),
]

lemoncurry/templates/lemoncurry/layout.html
{% load analytical compress favicon lemoncurry_tags meta static theme_colour %}<!doctype html>
<html dir="ltr" lang="en" class="{% block html_class %}{% endblock %}">
	<head{% meta_namespaces %}>{% site_name as site_name %}{% request_uri request as uri %}{% request_origin request as origin %}
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

		<base href="{{ origin }}" />
		<link rel="canonical" href="{{ uri }}" />
		<title class="p-name">{% if title %}{{ title }} ~ {% endif %}{{ site_name }}</title>

		{% analytical_head_top %}
		{% if atom %}<link rel="alternate" type="application/atom+xml" href="{{ atom }}" />{% endif %}
		{% if rss %}<link rel="alternate" type="application/rss+xml" href="{{ rss }}" /> {% endif %}
		{% block head %}{% endblock %}

		<link rel="authorization_endpoint" href="{{ origin }}{% url 'lemonauth:indie' %}" />
		<link rel="token_endpoint" href="{{ origin }}{% url 'lemonauth:token' %}" />
		<link rel="micropub" href="{{ origin }}{% url 'micropub:micropub' %}" />
		<link rel="openid.delegate" href="{{ origin }}" />
		<link rel="openid.server" href="https://openid.indieauth.com/openid" />

		<link rel="hub" href="{% get_push_hub %}" />
		<link rel="self" href="{{ uri }}" />

		<link rel="manifest" href="{% url 'wellknowns:manifest' %}" />
		<meta name="theme-color" content="{% theme_colour 2 %}" />
		{% get_package_json as package %}
		<meta name="generator" content="{{ package.name }} {{ package.version }}" />

		<meta property="og:url" content="{{ uri }}" />
		<meta property="og:title" content="{% firstof title site_name %}" />
		{% include 'meta/meta.html' %}
		{% get_favicons 'favicon/' %}

		<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
					integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous" />
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/monokai.min.css"
					integrity="sha384-bHqbpRh/XW+phptvH9nQvMKHwPH1ZbOxpIeAB2D2OIEL4Ni7aZzZgMFpsRra+v1g" crossorigin="anonymous" />
		<link rel="stylesheet" type="text/css" href="https://unpkg.com/openwebicons@1.4.3/css/openwebicons.min.css"
					integrity="sha384-Ljk0G9f8GyEhAzrdHNkQc89A/Kpq+sy09gejdAPyMyTDnPe4aDfS/ppZ/rDGM0Y9" crossorigin="anonymous" />
		<link rel="stylesheet" type="text/css" href="https://unpkg.com/tippy.js@2.5.2/dist/tippy.css"
					integrity="sha384-JsezPuW/bNd38848K5/8rIEbB+23QGQ8faCF8xEmjFT3i1qujgGiewfYevzMO3J1" crossorigin="anonymous" />
		{% compress css %}
		<link rel="stylesheet" type="text/stylus" href="{% static 'lemoncurry/css/layout.styl' %}" />
		{% block styles %}{% endblock %}
		{% endcompress %}
		<script type="text/javascript" defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js"
						integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe" crossorigin="anonymous"></script>
		{% analytical_head_bottom %}
	</head>
	<body{% block body_attr %}{% endblock %}>
		{% analytical_body_top %}
		<header>
			<nav class="navbar navbar-expand-md navbar-dark">
				<a class="navbar-brand" rel="home" href="{% url 'home:index' %}">{% site_name %}</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar"
								aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbar">
					{% block nav_left %}{% nav_left request %}{% endblock %}
					{% block nav_right %}{% nav_right request %}{% endblock %}
				</div>
			</nav>
			{% if request.resolver_match.view_name %}
			{% nav_crumbs request.resolver_match %}
			{% endif %}
		</header>

		<main>
			{% block main %}{% endblock %}
		</main>

		<footer>
			<p>all content licensed under <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">cc by-sa 4.0</a></p>

			{% if entries.has_other_pages %}
			<nav>
				<ul class="pagination">
					{% if entries.prev %}
					<li class="page-item">
						<a class="page-link" rel="prev" href="{{ entries.prev.url }}">
							<i class="fas fa-step-backward"></i><span class="sr-only">previous page</span>
						</a>
					</li>
					{% endif %}

					{% for page in entries.pages %}
					{% if page.current %}
					<li class="page-item active">
						<span class="page-link">{{ page.i }} <span class="sr-only">(current page)</span></span>
					</li>
					{% else %}
					<li class="page-item">
						<a class="page-link" href="{{ page.url }}">{{ page.i }}</a>
					</li>
					{% endif %}
					{% endfor %}

					{% if entries.next %}
					<li class="page-item">
						<a class="page-link" rel="next" href="{{ entries.next.url }}">
							<i class="fas fa-step-forward"></i><span class="sr-only">next page</span>
						</a>
					</li>
					{% endif %}
				</ul>
			</nav>
			{% endif %}

			<p>powered by <a rel="code-repository" href="{{ package.repository }}/tree/v{{ package.version }}">{{ package.name }} {{ package.version }}</a></p>
		</footer>

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" crossorigin="anonymous"
						integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" crossorigin="anonymous"
						integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" crossorigin="anonymous"
						integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" crossorigin="anonymous"
						integrity="sha384-ZeLYJ2PNSQjvogWP559CDAf02Qb8FE5OyQicqtz/+UhZutbrwyr87Be7NPH/RgyC"></script>
		<script src="https://unpkg.com/tippy.js@2.5.2/dist/tippy.standalone.min.js" crossorigin="anonymous"
						integrity="sha384-VEMCz3fC5atUNN+ezSHq2AZIBciT3aWGEZsStnW58gtO9PYb3wenWsYNoxLTbi/M"></script>

		{% compress js %}
		<script type="text/javascript">
			hljs.initHighlightingOnLoad();
		</script>
		{% block foot %}{% endblock %}
		{% endcompress %}
		{% analytical_body_bottom %}
	</body>
</html>