home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('page/<int:page>', views.index, name='index'),
    path('robots.txt', views.robots, name='robots.txt'),
]

lemonauth/urls.py
from django.urls import path
from . import views

app_name = 'lemonauth'
urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('indie', views.IndieView.as_view(), name='indie'),
    path('indie/approve', views.indie_approve, name='indie_approve'),
    path('token', views.TokenView.as_view(), name='token'),
]

lemonauth/views/indie.py
from annoying.decorators import render_to
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from lemoncurry import breadcrumbs, requests, utils
from urllib.parse import urlencode, urljoin, urlunparse, urlparse

from .. import tokens

breadcrumbs.add('lemonauth:indie', parent='home:index')


def canonical(url):
    (scheme, loc, path, params, q, fragment) = urlparse(url)
    if not path:
        path = '/'
    if not loc:
        loc, path = path, ''
    if not scheme:
        scheme = 'https'
    return urlunparse((scheme, loc, path, params, q, fragment))


@method_decorator(csrf_exempt, name='dispatch')
class IndieView(TemplateView):
    template_name = 'lemonauth/indie.html'
    required_params = ('me', 'client_id', 'redirect_uri')

    @method_decorator(login_required)
    @method_decorator(render_to(template_name))
    def get(self, request):
        params = request.GET.dict()
        params.setdefault('response_type', 'id')

        for param in self.required_params:
            if param not in params:
                return utils.bad_req(
                    'parameter {0} is required'.format(param)
                )

        me = canonical(params['me'])
        user = urljoin(utils.origin(request), request.user.url)
        if user != me:
            return utils.forbid(
                'you are logged in but not as {0}'.format(me)
            )

        redirect_uri = urljoin(params['client_id'], params['redirect_uri'])

        type = params['response_type']
        if type not in ('id', 'code'):
            return utils.bad_req(
                'unknown response_type: {0}'.format(type)
            )

        scopes = ()
        if type == 'code':
            if 'scope' not in params:
                return utils.bad_req(
                    'scopes required for code type'
                )
            scopes = params['scope'].split(' ')

        client = requests.mf2(params['client_id'])
        rels = (client.to_dict()['rel-urls']
                .get(redirect_uri, {})
                .get('rels', ()))
        verified = 'redirect_uri' in rels

        try:
            app = client.to_dict(filter_by_type='h-x-app')[0]['properties']
        except IndexError:
            app = None

        return {
            'app': app,
            'me': me,
            'redirect_uri': redirect_uri,
            'verified': verified,
            'params': params,
            'scopes': scopes,
            'title': 'indieauth from {client_id}'.format(**params),
        }

    def post(self, request):
        post = request.POST.dict()
        try:
            code = tokens.decode(post.get('code'))
        except Exception:
            # if anything at all goes wrong when decoding the auth code, bail
            # out immediately.
            return utils.forbid('invalid auth code')

        if code['typ'] != 'id':
            return utils.bad_req(
                'this endpoint only supports response_type=id'
            )
        if code['cid'] != post.get('client_id'):
            return utils.forbid('client id did not match')
        if code['uri'] != post.get('redirect_uri'):
            return utils.forbid('redirect uri did not match')

        user = get_user_model().objects.get(pk=code['uid'])
        me = urljoin(utils.origin(request), user.url)
        # If we got here, it's valid! Yay!
        return utils.choose_type(request, {'me': me}, {
            'application/x-www-form-urlencoded': utils.form_encoded_response,
            'application/json': JsonResponse,
        })


@login_required
@require_POST
def approve(request):
    params = {
        'me': urljoin(utils.origin(request), request.user.url),
        'code': tokens.gen_auth_code(request),
    }
    if 'state' in request.POST:
        params['state'] = request.POST['state']

    uri = request.POST['redirect_uri']
    sep = '&' if '?' in uri else '?'
    return redirect(uri + sep + urlencode(params))

lemonauth/views/login.py
import django.contrib.auth.views
from otp_agents.forms import OTPAuthenticationForm
from lemoncurry import breadcrumbs

breadcrumbs.add(route='lemonauth:login', label='log in', parent='home:index')

login = django.contrib.auth.views.LoginView.as_view(
    authentication_form=OTPAuthenticationForm,
    extra_context={'title': 'log in'},
    template_name='lemonauth/login.html',
    redirect_authenticated_user=True,
)

lemonauth/views/logout.py
import django.contrib.auth.views

logout = django.contrib.auth.views.LogoutView.as_view()

lemonauth/views/token.py
from django.contrib.auth import get_user_model
from django.views import View
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from urllib.parse import urljoin

from .. import tokens
from lemoncurry import utils


@method_decorator(csrf_exempt, name='dispatch')
class TokenView(View):
    def get(self, req):
        token = tokens.auth(req)
        if hasattr(token, 'content'):
            return token
        res = {
            'me': token.me,
            'client_id': token.client,
            'scope': token.scope,
        }
        return utils.choose_type(req, res)

    def post(self, req):
        post = req.POST
        try:
            code = tokens.decode(post.get('code'))
        except Exception:
            return utils.forbid('invalid auth code')

        if code['typ'] != 'code':
            return utils.bad_req(
                'this endpoint only supports response_type=code'
            )
        if code['cid'] != post.get('client_id'):
            return utils.forbid('client id did not match')
        if code['uri'] != post.get('redirect_uri'):
            return utils.forbid('redirect uri did not match')

        user = get_user_model().objects.get(pk=code['uid'])
        me = urljoin(utils.origin(req), user.url)
        if me != post.get('me'):
            return utils.forbid('me did not match')

        return utils.choose_type(req, {
            'access_token': tokens.gen_token(code),
            'me': me,
            'scope': code['sco'],
        })

lemonauth/templates/lemonauth/indie.html
{% extends 'lemoncurry/layout.html' %}
{% load markdown static %}

{% block styles %}
<link rel="stylesheet" type="text/stylus" href="{% static 'lemonauth/css/indie.styl' %}" />
{% endblock %}

{% block main %}
<div class="container">
	<form class="card" method="post" action="{% url 'lemonauth:indie_approve' %}">
		<h4 class="card-header h-x-app">
			{% if app %}<img class="u-logo p-name" src="{{ app.logo | first }}" alt="{{ app.name | first }}" />{% endif %}
			sign in to
			{% if app %}{{ app.name | first }}{% endif %}
			{% if app %}({% endif %}<a class="u-url code{% if not app %} p-name{% endif %}" href="{{ params.client_id }}">{{ params.client_id }}</a>{% if app %}){% endif %}?
			{% if verified %}
			<span data-tooltip data-tippy-theme="dark success" data-tippy-html="#verified-success">
				<i class="fas fa-check-circle verified-success"></i>
			</span>
			{% else %}
			<span data-tooltip data-tippy-theme="dark warning" data-tippy-html="#verified-warning">
				<i class="fas fa-question-circle verified-warning"></i>
			</span>
			{% endif %}
		</h4>

		<div class="card-body">
			<p class="card-text">do you want to confirm your identity, <a class="code" href="{{ me }}">{{ me }}</a>, with this app?</p>
			{% if params.response_type == 'code' %}
			<p class="card-text">additionally, this app is requesting the following <i>scopes</i> - you can edit the scopes that will be granted to the app, if you wish</p>
			<div class="card-text form-group">
			{% for scope in scopes %}
			<div class="form-check">
				<input class="form-check-input" id="scopes-{{ scope }}" name="scope" type="checkbox" checked value="{{ scope }}" />
				<label class="form-check-label" for="scopes-{{ scope }}">{{ scope }}</label>
			</div>
			{% endfor %}
			</div>
			{% endif %}
			<p class="card-text"><small>you will be redirected to <a class="code" href="{{ redirect_uri }}">{{ redirect_uri }}</a> after authorising this app</small></p>
		</div>

		<div class="card-footer">
			<button class="btn btn-success" type="submit">
				<i class="fas fa-check"></i>
				approve
			</button>
		</div>

		{% csrf_token %}
		<input name="me" type="hidden" value="{{ me }}" />
		<input name="client_id" type="hidden" value="{{ params.client_id }}" />
		<input name="redirect_uri" type="hidden" value="{{ redirect_uri }}" />
		{% if params.state %}<input name="state" type="hidden" value="{{ params.state }}" />{% endif %}
		<input name="response_type" type="hidden" value="{{ params.response_type }}" />
	</form>
</div>

<div id="verified-success" hidden>
	this client has been <strong>verified</strong> using <code>{{ '<link rel="redirect_uri">' | force_escape }}</code> - they are who they claim to be!
</div>
<div id="verified-warning" hidden>
	this client could <strong>not</strong> be verified using <code>{{ '<link rel="redirect_uri">' | force_escape }}</code> - check the redirect uri carefully yourself!
</div>
{% endblock %}
{% block foot %}
<script type="text/javascript">
	tippy('[data-tippy-theme]', {arrow: true});
</script>
{% endblock %}

lemonauth/templates/lemonauth/login.html
{% extends 'lemoncurry/layout.html' %}
{% load lemonauth_tags static %}

{% block styles %}
<link rel="stylesheet" type="text/stylus" href="{% static 'lemonauth/css/login.styl' %}" />
{% endblock %}

{% block main %}
<div class="container">
	{% if form.errors %}
	<p class="alert alert-danger">
		<strong>Uh oh!</strong> Your username and password didn't match. Please try again.
	</p>
	{% endif %}

	{% if next %}
	{% if user.is_authenticated %}
	<p class="alert alert-warning">
		<strong>Hang on!</strong> Your account doesn't have access to this page. To proceed, please log in to an account that does have access.
	</p>
	{% else %}
	<p class="alert alert-warning">
		<strong>Oops!</strong> Please log in to see this page.
	</p>
	{% endif %}
	{% endif %}

	<form class="card" method="post" action="{% url 'lemonauth:login' %}">
		<div class="card-body">
			{% form_field form.username %}
			{% form_field form.password %}
			{% form_field form.otp_token %}

			<div class="form-group form-check">
				<input id="id_{{ form.otp_trust_agent.name }}" name="{{ form.otp_trust_agent.name }}" class="form-check-input" type="checkbox" />
				<label for="id_{{ form.otp_trust_agent.name }}" class="form-check-label">remember this browser (don't tick this on a public computer!)</label>
			</div>
		</div>

		<div class="card-footer">
			<button class="btn btn-primary" type="submit">
				<i class="fas fa-sign-in-alt"></i>
				log in
			</button>
		</div>

		{% csrf_token %}
		<input type="hidden" name="next" value="{{ next }}" />
	</form>
</div>
{% endblock %}